name: CI

on:
  push:
    branches: [ master ]
    paths-ignore:
      - 'doc/**'
      - 'README.md'
      - '.readthedocs.yaml'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - 'doc/**'
      - 'README.md'
      - '.readthedocs.yaml'
  workflow_dispatch:

jobs:
  ubuntu-2004:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Install Qt
        uses: jurplel/install-qt-action@v2.14.0

      - name: Setup OpenCV
        uses: Dovyski/setup-opencv-action@v1

      - name: Install prerequisites
        run: |
          sudo apt update
          sudo apt install -y make gcc

      - name: Build all
        run: |
          sed -i 's/QT_DIR=\/opt/QT_DIR=$(cd "$(dirname "$0")";pwd)/g' build_deb.sh
          sed -i 's/\/home\/xiaoming\/Desktop\/opencv/\/usr\/local/g' build_deb.sh
          sed -i 's/\/home\/xiaoming\/Desktop\/opencv/\/usr\/local/g' partform_unix.pri
          ./build_deb.sh

      - name: Upload build asserts
        uses: actions/upload-artifact@v2.2.4
        with:
          name: YUVviewer_Linux.deb
          path: |
            ./dpkg/*.deb

  windows:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v2

      - name: Install Qt
        uses: jurplel/install-qt-action@v2.14.0
        with:
          arch: win64_mingw81
          
      - name: Install prerequisites
        run: |
          Choco-Install -PackageName innosetup --force
          Choco-Install -PackageName cmake --force
          git clone https://github.com/opencv/opencv.git --branch 4.0.0 --depth 1
          cmake -G "MinGW Makefiles" -S opencv -B opencv/build -D CMAKE_INSTALL_PREFIX=C:/opencv4.0.0 -D WITH_TBB=ON -D WITH_IPP=ON -D BUILD_NEW_PYTHON_SUPPORT=OFF -D WITH_V4L=OFF -D ENABLE_PRECOMPILED_HEADERS=ON -D INSTALL_C_EXAMPLES=OFF -D INSTALL_PYTHON_EXAMPLES=OFF -D BUILD_EXAMPLES=OFF -D WITH_QT=OFF -D WITH_OPENGL=OFF
          mingw32-make
          mingw32-make install

      - name: Build all
        run: |
          ./tools/sed/sed.exe -i "s/QT_DIR=C:\/Qt\/Qt5.12.8\/5.12.8\/mingw73_32\/bin/QT_DIR=%Qt5_Dir%/g" ./build_setup.bat
          ./tools/sed/sed.exe -i "s/QT_TOOLS_DIR=C:\/Qt\/Qt5.12.8\/Tools\/mingw730_32\/bin/QT_TOOLS_DIR=C:\/ProgramData\/Chocolatey\/lib\/mingw\/tools\/install\/mingw64\/x86_64-w64-mingw32\/bin/g" ./build_setup.bat
          ./tools/sed/sed.exe -i "s/OPENCV_DIR=D:\/Qt\/opencv4.2.0\/x64\/mingw\/bin/OPENCV_DIR=C:\/opencv4.0.0\/x64\/mingw\/bin/g" ./build_setup.bat
          ./tools/sed/sed.exe -i "s/OPENCV_DIR=D:\/Qt\/opencv4.2.0/OPENCV_DIR=C:\/opencv4.0.0/g" ./partform_win32.pri
          ./build_setup.bat

      - name: Upload build asserts
        uses: actions/upload-artifact@v2.2.4
        with:
          name: YUVviewer_setup.exe
          path: |
            ./InnoSetup/YUVviewer_setup.exe
